plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'com.hypherionmc.modutils.modpublisher' version '2.1.8'
}

base {
    archivesName = "siege-machines-${minecraft_version}-fabric"
}

dependencies {
    modCompileOnly("mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}")
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")
    modImplementation "me.shedaniel:RoughlyEnoughItems-fabric:$rei_version"

    modImplementation "software.bernie.geckolib:geckolib-fabric-${rootProject.minecraft_version}:${rootProject.geckolib_version}"

    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation "me.shedaniel:RoughlyEnoughItems-fabric:$rei_version"
    modImplementation "dev.architectury:architectury-fabric:$architectury_version"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:$rootProject.neoforge_config_api_version"

    implementation 'com.google.code.findbugs:jsr305:3.0.2'
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publisher {
    def mcVersionsNeo = (rootProject.ext.minecraftGameVersions as List).collect { it.toString() } as String[]
    def changelogFile = rootProject.file("fabric/CHANGELOG.md")
    def changelogText = changelogFile.exists() ? changelogFile.getText("UTF-8") : ""

    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSEFORGE_TOKEN")
    }

    setCurseID((rootProject.findProperty("mod_curseforge_id") ?: "").toString())

    setModrinthID((rootProject.findProperty("mod_modrinth_id") ?: "").toString())

    setVersionType((rootProject.findProperty("release_channel") ?: "release").toString())

    setChangelog(changelogText)

    setProjectVersion(rootProject.version)

    setDisplayName("[${rootProject.minecraft_version}-fabric]-${rootProject.mod_display_name}-${rootProject.version}")

    setGameVersions(*mcVersionsNeo)

    setLoaders("fabric")

    setCurseEnvironment("both")

    setArtifact(tasks.remapJar)

    modrinthDepends {
        required("architectury-api")
        required("geckolib")
        required("forge-config-api-port")
        optional("patchouli")
    }

    curseDepends {
        required("architectury-api")
        required("geckolib")
        required("forge-config-api-port")
        optional("patchouli")
    }
}
