# Project
group=io.github.magistu
java_version=21

# Common
minecraft_version=1.21.1
minecraft_min_version=1.21.1
minecraft_max_version=1.21.2
parchment_minecraft=1.21
parchment_version=2024.06.23
neo_form_version=1.21-20240613.152323

# Mod properties
version=1.30
mod_name=SiegeMachines
mod_display_name=Siege-Machines
mod_id=siegemachines
license=CC0-1.0
mod_author=Magistu
credits=Lexiolty, Goodbird, itzme1on, Sahgar
description=Adds medieval siege machines
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/medieval-siege-machines
mod_issues_url=https://github.com/Magistu/Siege-Machines/issues
mod_git_url=https://github.com/Magistu/Siege-Machines
mod_discord_url=https://discord.gg/R8U8Hpgr75
mod_curseforge_id=585964
mod_modrinth_id=ctnEXZ5V

# Fabric
fabric_version=0.104.0+1.21.1
fabric_loader_version=0.16.3

# NeoForge
neoforge_version=21.1.123
neoforge_version_range=[21.1.20,)
neoforge_loader_version_range=[4,)

# Other mods
jei_version=19.24.0.317
rei_version=16.0.729
cloth_config_version=15.0.127
architectury_version=13.0.3
geckolib_version=4.7
neoforge_config_api_version=21.1.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
