modLoader="javafml" #mandatory
loaderVersion="${forge_version_range}" #mandatory
license="${license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
# A display name for the mod
displayName="${description}" #mandatory
# logoFile="siegemachines.png" #optional // TODO Logo
credits="${credits}"
authors="${mod_author}" #optional
description='''${description}'''
[[dependencies.siegemachines]]
modId = "minecraft"
versionRange = "[${minecraft_min_version},${minecraft_max_version})"
mandatory = true
side = "BOTH"
ordering = "NONE"

[[dependencies.siegemachines]]
modId = "forge"
versionRange = "${forge_version_range}"
mandatory = true
side = "BOTH"
ordering = "NONE"