modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="siegemachines"
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Medieval Siege Machines" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="siegemachines.png" #optional
# A text field displayed in the mod UI
credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="Magistu, itzme1on" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''Adds medieval siege machines'''
[[dependencies.siegemachines]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.54,)"
    ordering="NONE"
    side="BOTH"
