modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="siegemachines" #mandatory
version="1.16-1.17" #mandatory
displayName="Medieval Siege Machines" #mandatory
authors="Magistu" #optional
credits="Lexiolty" #optional
description='''Adds medieval siege machines'''
[[dependencies.siegemachines]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.56,]"
    ordering="NONE"
    side="BOTH"