modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="siegemachines" #mandatory
version="${version}" #mandatory
# A display name for the mod
displayName="Medieval Siege Machines" #mandatory
# logoFile="siegemachines.png" #optional // TODO Logo
credits="Lexiolty, itzme1on, Sahgar"
authors="Magistu" #optional
description='''Adds medieval siege machines'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.siegemachines]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.00,]"
    ordering="NONE"
    side="BOTH"