modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="siegemachines"
version="${file.jarVersion}"
displayName="Medieval Siege Machines"
logoFile="siegemachines.png"
credits="Models by Lexiolty"
authors="Magistu, itzme1on"
description='''Adds medieval siege machines to your beauty Minecraft world!'''
[[dependencies.siegemachines]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.00,]"
    ordering="NONE"
    side="BOTH"