modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="${license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
# A display name for the mod
displayName="${mod_title}" #mandatory
# logoFile="siegemachines.png" #optional // TODO Logo
credits="${credits}"
authors="${mod_author}" #optional
description='''${mod_description}'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.siegemachines]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.7,]"
    ordering="NONE"
    side="BOTH"